apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: es-operator-demo
data:
  opensearch.yml: |
    cluster.name: es-cluster
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.seed_hosts: [es-master]
    cluster.initial_master_nodes: [es-master-0]
    plugins.security.ssl.transport.pemcert_filepath: esnode.pem
    plugins.security.ssl.transport.pemkey_filepath: esnode-key.pem
    plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
    plugins.security.ssl.transport.enforce_hostname_verification: false
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemcert_filepath: esnode.pem
    plugins.security.ssl.http.pemkey_filepath: esnode-key.pem
    plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem
    plugins.security.allow_unsafe_democertificates: true
    plugins.security.allow_default_init_securityindex: true
    plugins.security.authcz.admin_dn:
      - CN=kirk,OU=client,O=client,L=test, C=de

    plugins.security.audit.type: internal_opensearch
    plugins.security.enable_snapshot_restore_privilege: true
    plugins.security.check_snapshot_restore_write_privileges: true
    plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
    plugins.security.system_indices.enabled: true
    plugins.security.system_indices.indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opendistro-asynchronous-search-response*"]
    #node.max_local_storage_nodes: 3
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-master
  namespace: es-operator-demo
spec:
  replicas: 1
  serviceName: es-master
  selector:
    matchLabels:
      application: elasticsearch
      role: master
  template:
    metadata:
      labels:
        application: elasticsearch
        role: master
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 50Mi
            cpu: 50m
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: "opensearchproject/opensearch:1.0.0"
        env:
          - name: "node.name"
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          # the performance analyzer was failing with this
          #- name: "ES_JAVA_OPTS"
          #  value: "-Xmx400m -Xms400m"
          - name: node.master
            value: "true"
          - name: node.data
            value: "false"
        readinessProbe:
          exec:
            command:
              - bash
              - -c
              - curl -XGET https://localhost:9200/_cluster/health?local=true --insecure -u admin:admin
          initialDelaySeconds: 20
        ports:
        - containerPort: 9200
          name: es-http
        - containerPort: 9300
          name: es-transport
        volumeMounts:
          - name: es-data
            mountPath: /usr/share/opensearch/data
          - name: elasticsearch-config
            mountPath: /usr/share/opensearch/config/opensearch.yml
            subPath: opensearch.yml
      volumes:
        - name: es-data
          emptyDir: {}
        - name: elasticsearch-config
          configMap:
            name: es-config
            items:
              - key: opensearch.yml
                path: opensearch.yml
---
apiVersion: v1
kind: Service
metadata:
  name: es-http
  namespace: es-operator-demo
spec:
  selector:
    application: elasticsearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: es-master
  namespace: es-operator-demo
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    application: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
