apiVersion: zalando.org/v1
kind: ElasticsearchDataSet
metadata:
  labels:
    application: elasticsearch
    role: data
    group: simple
  name: es-data-simple
  namespace: es-operator-demo
spec:
  replicas: 1
  scaling:
    enabled: false
  template:
    metadata:
      labels:
        application: elasticsearch
        role: data
        group: simple
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: elasticsearch
        env:
        - name: "node.name"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "node.attr.group"
          value: "simple"
        - name: "node.master"
          value: "false"
        - name: "node.data"
          value: "true"
        #- name: "ES_JAVA_OPTS"
        #  value: "-Xmx500m -Xms500m"
        image: "opensearchproject/opensearch:1.0.0"
        ports:
        - containerPort: 9300
          name: transport
        readinessProbe:
          exec:
            command:
              - bash
              - -c
              - curl -XGET https://localhost:9200/_cluster/health?local=true --insecure -u admin:admin
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: data
        - name: elasticsearch-config
          mountPath: /usr/share/opensearch/config/opensearch.yml
          subPath: opensearch.yml
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: busybox:1.30
        name: init-sysctl
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          runAsUser: 0
          privileged: true
      volumes:
      - name: data
        emptyDir: {}
      - name: elasticsearch-config
        configMap:
          name: es-config
          items:
          - key: opensearch.yml
            path: opensearch.yml
